import { useState } from 'react';

const t = { title: '\uB85C\uADF8\uC778', username: '\uC544\uC774\uB514', password: '\uBE44\uBC00\uBC88\uD638', cancel: '\uCDE8\uC18C', submit: '\uB85C\uADF8\uC778', loading: '\uB85C\uADF8\uC778 \uC911...', fallback: '\uB85C\uADF8\uC778\uC5D0 \uC2E4\uD328\uD588\uC2B5\uB2C8\uB2E4.' };

export default function LoginModal({ open, onClose, onLogin }) {
  const [username, setUsername] = useState(''); const [password, setPassword] = useState(''); const [loading, setLoading] = useState(false); const [error, setError] = useState(null);
  if (!open) return null;
  const submit = async (event) => { event.preventDefault(); setLoading(true); setError(null); try { await onLogin({ username, password }); onClose(); } catch (err) { setError(err.message || t.fallback); } finally { setLoading(false); } };
  return <div className="fixed inset-0 z-50 flex items-center justify-center bg-slate-950/40 px-4"><div className="w-full max-w-sm rounded-lg border border-slate-200 bg-white p-6 shadow-xl"><h3 className="text-xl font-bold">{t.title}</h3>{error && <p className="mt-4 rounded-md border border-red-200 bg-red-50 p-3 text-sm text-red-700">{error}</p>}<form onSubmit={submit} className="mt-5 space-y-3"><input value={username} onChange={(event) => setUsername(event.target.value)} placeholder={t.username} required autoComplete="username" className="h-11 w-full rounded-md border border-slate-300 px-3 text-sm outline-none focus:border-blue-500" /><input value={password} onChange={(event) => setPassword(event.target.value)} placeholder={t.password} required type="password" autoComplete="current-password" className="h-11 w-full rounded-md border border-slate-300 px-3 text-sm outline-none focus:border-blue-500" /><div className="flex gap-2 pt-2"><button type="button" onClick={onClose} className="h-11 flex-1 rounded-md border border-slate-300 text-sm font-semibold text-slate-700">{t.cancel}</button><button type="submit" disabled={loading} className="h-11 flex-1 rounded-md bg-blue-600 text-sm font-semibold text-white disabled:opacity-50">{loading ? t.loading : t.submit}</button></div></form></div></div>;
}
