import { useState } from 'react';

const t = { title: '\uD68C\uC6D0\uAC00\uC785', intro: '\uD544\uC218 \uC815\uBCF4\uB97C \uC785\uB825\uD558\uACE0 \uC11C\uBE44\uC2A4\uB97C \uC2DC\uC791\uD558\uC138\uC694.', username: '\uC544\uC774\uB514', password: '\uBE44\uBC00\uBC88\uD638', confirm: '\uBE44\uBC00\uBC88\uD638 \uD655\uC778', name: '\uC774\uB984', email: '\uC774\uBA54\uC77C', phone: '\uD734\uB300\uD3F0 \uBC88\uD638', birth: '\uC0DD\uB144\uC6D4\uC77C', consent: '\uAC1C\uC778\uC815\uBCF4 \uC218\uC9D1 \uBC0F \uC774\uC6A9\uC5D0 \uB3D9\uC758\uD569\uB2C8\uB2E4.', cancel: '\uCDE8\uC18C', submit: '\uAC00\uC785\uD558\uAE30', loading: '\uAC00\uC785 \uC911...', mismatch: '\uBE44\uBC00\uBC88\uD638\uAC00 \uC77C\uCE58\uD558\uC9C0 \uC54A\uC2B5\uB2C8\uB2E4.' };
const initial = { username: '', password: '', passwordConfirm: '', name: '', email: '', phone: '', birthDate: '', consent: false };

export default function SignupModal({ open, onClose, onSignup }) {
  const [form, setForm] = useState(initial); const [loading, setLoading] = useState(false); const [error, setError] = useState(null);
  if (!open) return null;
  const update = (field) => (event) => setForm((value) => ({ ...value, [field]: event.target.type === 'checkbox' ? event.target.checked : event.target.value }));
  const submit = async (event) => { event.preventDefault(); setLoading(true); setError(null); try { if (form.password !== form.passwordConfirm) throw new Error(t.mismatch); const profile = { ...form }; delete profile.passwordConfirm; await onSignup(profile); setForm(initial); onClose(); } catch (err) { setError(err.message); } finally { setLoading(false); } };
  const field = 'h-11 w-full rounded-md border border-slate-300 px-3 text-sm outline-none focus:border-blue-500';
  return <div className="fixed inset-0 z-50 flex items-center justify-center bg-slate-950/40 px-4 py-6"><div className="max-h-full w-full max-w-lg overflow-y-auto rounded-lg border border-slate-200 bg-white p-6 shadow-xl"><h3 className="text-xl font-bold">{t.title}</h3><p className="mt-1 text-sm text-slate-500">{t.intro}</p>{error && <p className="mt-4 rounded-md border border-red-200 bg-red-50 p-3 text-sm text-red-700">{error}</p>}<form onSubmit={submit} className="mt-5 grid gap-3 sm:grid-cols-2"><input value={form.username} onChange={update('username')} placeholder={t.username} minLength={4} required className={field} /><input value={form.name} onChange={update('name')} placeholder={t.name} required className={field} /><input value={form.password} onChange={update('password')} placeholder={t.password} minLength={8} required type="password" className={field} /><input value={form.passwordConfirm} onChange={update('passwordConfirm')} placeholder={t.confirm} minLength={8} required type="password" className={field} /><input value={form.email} onChange={update('email')} placeholder={t.email} required type="email" className={`${field} sm:col-span-2`} /><input value={form.phone} onChange={update('phone')} placeholder={t.phone} required type="tel" className={field} /><label className="text-xs text-slate-500"><span>{t.birth}</span><input value={form.birthDate} onChange={update('birthDate')} type="date" className={`${field} mt-1`} /></label><label className="flex gap-2 text-sm text-slate-600 sm:col-span-2"><input checked={form.consent} onChange={update('consent')} required type="checkbox" /><span>{t.consent}</span></label><div className="flex gap-2 pt-2 sm:col-span-2"><button type="button" onClick={onClose} className="h-11 flex-1 rounded-md border border-slate-300 text-sm font-semibold text-slate-700">{t.cancel}</button><button type="submit" disabled={loading} className="h-11 flex-1 rounded-md bg-blue-600 text-sm font-semibold text-white disabled:opacity-50">{loading ? t.loading : t.submit}</button></div></form></div></div>;
}
